### ISSUE TITLE
how it is support in android os ,sorry im bad in English

### ISSUE THREAD

**Issue by ghost** [assembly/cordova-cookie-jar#2]

**Comment by foysavas** [comment]
It doesn't have Android support yet. You can add it using Java. Take a look at [this repo](https://github.com/bez4pieci/Phonegap-Cookies-Plugin) for inspiration.

现在还没有Android支持。你可以用Java加它。看[这个仓库](https://github.com/bez4pieci/Phonegap-Cookies-Plugin)给你灵感。

**Comment by ghost** [comment]
谢谢
